// Alphabetical list of common exercises to power the ExercisePicker.
// Each item has a stable id (slug) and a human-friendly name.
export const EXERCISES = [
  { id: 'australian-pull-up', name: 'Australian Pull-Up' },
  { id: 'back-extension', name: 'Back Extension' },
  { id: 'barbell-bench-press', name: 'Barbell Bench Press' },
  { id: 'barbell-row', name: 'Barbell Row' },
  { id: 'barbell-squat', name: 'Barbell Back Squat' },
  { id: 'bench-press-variations', name: 'Bench Press (variation)' },
  { id: 'bp-dumbbell-fly', name: 'Dumbbell Fly' },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat' },
  { id: 'calf-raise', name: 'Calf Raise' },
  { id: 'close-grip-push-up', name: 'Close-Grip Push-Up' },
  { id: 'curls-barbell', name: 'Barbell Curl' },
  { id: 'curls-concentration', name: 'Concentration Curl' },
  { id: 'deadlift', name: 'Deadlift' },
  { id: 'dips', name: 'Dips' },
  { id: 'incline-bench-press', name: 'Incline Barbell Bench Press' },
  { id: 'leg-press', name: 'Leg Press' },
  { id: 'lateral-raise', name: 'Lateral Raise' },
  { id: 'lat-pull-down', name: 'Lat Pulldown' },
  { id: 'leg-extension', name: 'Leg Extension' },
  { id: 'leg-curl', name: 'Leg Curl' },
  { id: 'machine-row', name: 'Machine Row' },
  { id: 'mlb', name: 'Mule Kickback' },
  { id: 'overhead-press', name: 'Overhead Press' },
  { id: 'pace-press', name: 'Push Press' },
  { id: 'preacher-curl', name: 'Preacher Curl' },
  { id: 'rear-delt-row', name: 'Rear Delt Row' },
  { id: 'row-machine', name: 'Seated Row (Machine)' },
  { id: 'seated-rows', name: 'Seated Cable Row' },
  { id: 'skullcrusher', name: 'Skullcrusher' },
  { id: 'snatch-grip-deadlift', name: 'Snatch-Grip Deadlift' },
  { id: 'squat', name: 'Back Squat' },
  { id: 'step-up', name: 'Step-Up' },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift' },
  { id: 'super-set', name: 'Super Set (General)' },
  { id: 't-bar-row', name: 'T-Bar Row' },
  { id: 'turkish-get-up', name: 'Turkish Get-Up' },
  { id: 'upright-row', name: 'Upright Row' },
  { id: 'weighted-pull-up', name: 'Weighted Pull-Up' },
  { id: 'calisthenics', name: 'Bodyweight Row' },
  { id: 'box-jump', name: 'Box Jump' },
  { id: 'bulgarian-one-leg', name: 'Bulgarian Split Squat (DB)' },
  { id: 'cable-cross-over', name: 'Cable Cross-Over' },
  { id: 'chest-supported-row', name: 'Chest-Supported Row' },
  { id: 'hip-thrust', name: 'Hip Thrust' },
  { id: 'glute-bridge', name: 'Glute Bridge' },
  { id: 'hip-extensions', name: 'Hip Extensions' },
  { id: 'hamstring-curl', name: 'Leg Curl (Hamstring)' },
  { id: 'hip-abduction', name: 'Hip Abduction' },
  { id: 'hip-please', name: 'Hip Thrust (DB)' },
  { id: 'isolated-bicep', name: 'Isolation Bicep Curl' },
  { id: 'isolation-tricep', name: 'Isolation Tricep Extension' },
  { id: 'kettlebell-swing', name: 'Kettlebell Swing' },
  { id: 'machine-press', name: 'Machine Press' },
  { id: 'mountain-climber', name: 'Mountain Climber' },
  { id: 'pull-up', name: 'Pull-Up' },
  { id: 'push-up', name: 'Push-Up' },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift' },
  { id: 'shoulder-press', name: 'Shoulder Press' },
  { id: 'sledgehammer', name: 'Sled Push' },
  { id: 'squat-clean', name: 'Front Squat' },
  { id: 'snatch', name: 'Snatch' },
  { id: 'squat-variation', name: 'Split Squat' },
  { id: 'step-down', name: 'Step-Down' },
  { id: 'sumo-squat', name: 'Sumo Squat' },
  { id: 'sandbag-press', name: 'Sandbag Overhead Press' },
  { id: 'single-arm-row', name: 'One-Arm Dumbbell Row' },
  { id: 'smith-machine-bench', name: 'Smith Machine Bench' },
  { id: 'turkish-get-up-2', name: 'Turkish Get-Up (DB)' },
  { id: 'weighted-dips', name: 'Weighted Dips' },
  { id: 'weighted-rows', name: 'Bent Over Barbell Row' },
  { id: 'yoke-walk', name: 'Yoke Walk' },
  // Dumbbell/DB focused list
  { id: 'db-bench-press', name: 'Dumbbell Bench Press' },
  { id: 'db-press', name: 'Dumbbell Overhead Press' },
  { id: 'db-row', name: 'Dumbbell Row' },
  { id: 'db-squat', name: 'Dumbbell Squat' },
  { id: 'db-lunges', name: 'Dumbbell Lunge' },
  { id: 'db-hip-circle', name: 'DB Hip Hinge' },
  // Core / core stabilization
  { id: 'plank', name: 'Plank' },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise' },
  { id: 'ab-wheel', name: 'Ab Wheel Rollout' },
  { id: 'russian-twist', name: 'Russian Twist' },
  { id: 'sit-up', name: 'Sit-Up' },
  // Cardio alternatives
  { id: 'bike', name: 'Stationary Bike' },
  { id: 'rower', name: 'Rowing Machine' },
  { id: 'treadmill', name: 'Treadmill Run' },
  // Variations & accessories
  { id: 'landmine-press', name: 'Landmine Press' },
  { id: 'face-pull', name: 'Face Pull' },
  { id: 'shrug', name: 'Shrug' },
  { id: 'farmer-warm', name: 'Farmer Walk' },
  { id: 'calisthenics', name: 'Calisthenics' },
  { id: 'cab', name: 'Cable Pulldown' },
];
export default EXERCISES;
